### ISSUE TITLE
一点疑问

### ISSUE THREAD

**Issue by GreenSheep-Studio** [eliphatfs/kbdmania#1]
你的项目太棒了！我是在b站看到up的视频，因为开源所以想试看看！
但是在使用过程中，我遇到一点问题：当我在cmd中键入”pip install -r requirements.txt“的时候，他告诉我：
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'就像下图这样
![image](https://user-images.githubusercontent.com/64400578/187327824-fc17c190-6984-4933-95fb-81c9271ba702.png)
我该怎么解决它{本人纯萌新
谢谢

**Comment by eliphatfs** [comment]
目录对吗，你看仓库下面有一个requirements.txt，要在那个目录下面运行
